[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200


lib_deps =
    majicdesigns/MD_Parola @ ^3.7.1
    majicdesigns/MD_MAX72XX @ ^3.5.1
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0.4